### ISSUE TITLE
Frontend implementation based on sample database

### ISSUE THREAD

**Issue by ruudgreven** [ruudgreven/robocodecup#3]

**Comment by TimothySealy** [comment]
Sample database can be loaded with test/test_data.js

**Comment by TimothySealy** [comment]
Added api call for inserting test data (/api/testdata). See https://github.com/ruudgreven/robocodecup/commit/003788b76a51ccd0220a87221d3af6aa6abd46d5#diff-b9faf54aea77256132b5e489bf8ffa54R18
