### ISSUE TITLE
Create a REST api based on Mongoose

### ISSUE THREAD

**Issue by ruudgreven** [ruudgreven/robocodecup#5]

**Comment by TimothySealy** [comment]
The following REST api's are up and running:
/api/competition
/api/competition?featured=true
/api/competition/useb_2017
/api/competition/useb_2017/team
/api/teams/
/api/teams/my_team

Only GET calls because we need to think about the authentication model for the create, update and deletes. Probably something like JWT.

**Comment by TimothySealy** [comment]
Even more api calls now:
/api/battle
/api/battle/my-team
/api/ranking
/api/ranking?competition=useb_2017
/api/ranking?competition=useb_2017&round=1
/api/ranking?round=1

**Comment by ruudgreven** [comment]
What do you mean with featured?
In my opinion the website always shows one competition (maybe in the future we can create a dropdown for multiple competitions and save the selection of the user on the client). 

Now i assume that's there only one featured competition and when the user loads the site that competition will be showed.

**Comment by TimothySealy** [comment]
The model was designed with multiple competitions in mind. There can be official and unofficial competitions. The idea behind the featured attribute is that when there are many competitions running you could have a small set (up to three competitions for example) you could highlight in the website. So in my mind the home page would display three lists: first the featured competitions, then the official competitions (which are not featured) and last the unofficial competitions (which are not featured). 

From a UI perspective you could make a slide show for the featured competitions (with some nice banners, which we would need to store in the database though, at least the link to the banner) and then a list of the top 5 official competitions. At the bottom of the page you could add a link to unofficial competitions (which would list all unofficial competitions only).

Of course in the first version we could build the site to only show details of one competition.

**Comment by TimothySealy** [comment]
Api's have been completely overhauled. See /apidoc for api description. Don't forget to generate it first.
