### ISSUE TITLE
Add rank # and played, won, lost and disqualified counts to /ranking

### ISSUE THREAD

**Issue by ruudgreven** [ruudgreven/robocodecup#6]
At this moment /ranking retrieves objects like this:

{
    "_id": "58a0014d095ba0e0c7045926",
    "code": "useb_2017",
    "round": 3,
    "__v": 0,
    "competition": "useb_2017",
    "teams": [
      {
        "points": 3,
        "team_name": "TimTeam",
        "_id": "58a026505ff5aa6ee2d76789"
      },
      {
        "points": 0,
        "team_name": "RudeTeam",
        "_id": "58a026505ff5aa6ee2d76788"
      }
    ]
  }

I would like to have the numbers of battles played in this round, and the number of battles the team has won, lost or has been disqualified for. The points fields can be computed by the won, lost and disqualified numbers (won = 3 points, lost = 1 point, disqualified = 0, so points = (no_won*3 + no_lost).

And the ranking number. So the one with the most points has number 1, the second number 2 and so on (Or can i determine this from the order of teams?).

So, something like this:

{
    "_id": "58a0014d095ba0e0c7045926",
    "code": "useb_2017",
    "round": 3,
    "__v": 0,
    "competition": "useb_2017",
    "teams": [
      {
        "rank": 1,
        "points": 3,
        "won": 1,
        "lost": 0,
        "disqualified": 0,
        "team_name": "TimTeam",
        "_id": "58a026505ff5aa6ee2d76789"
      },
      {
        "rank": 2,
        "points": 0,
        "team_name": "RudeTeam",
        "_id": "58a026505ff5aa6ee2d76788"
      }
    ]
  }

**Comment by TimothySealy** [comment]
Good point about the won, lost and disqualified. Will add that.

About the ranking number. The teams are ordered according to their ranking. The ranking number is not stored in the database. The reason for this is that if we implement groups then we can get the ranking per group simply by filtering the ranking while maintaining the order of the teams element.

If a number is needed we could implement it in the api call (simply add a number to every item in the list). We do have to take paging into account when implementing this. Come to think of it, a search function may also be useful to have.

**Comment by TimothySealy** [comment]
Rank number (op webpage) is now done with by auto number the items in the view. The numbers of battles played is now computed by the RankingUtil database script.

**Comment by TimothySealy** [comment]
Required data is now supplied in the battle results and stored in the database. Frontend still needs to be updated in order to display the information.
